// <auto-generated />
namespace RejestrOsobProjekt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class imageUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202105070917336_imageUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
